import images from "./images";

const description = [
  {
    category: "villa",
    specification: "Villa écologique en brique de terre en forme H",
    service: "Conception et construction",
    surface: "500 m2",
    dsc: [
      "Un grand Séjour parental",
      "une grande cuisine",
      " Une reserve",
      "Un bureau",
      "Un séjour pour enfants",
      "Une loge de gardien",
      "Trois chambres",
      "Trois Terrasses",
      "Deux douches",
      "Une toilette visiteur",
      "Une buanderie extérieur",
    ],
    imgUrl: [images.villa2, images.villa1],
  },
  {
    category: "villa",
    specification: "Conception d'une villa de type F4",
    service: "Conception et construction",
    surface: "250 m2",
    dsc: [
      "Trois Chambres avec douche dans chacune",
      "une grande cuisine",
      " Un grand salon",
      "Une salle à manger",
      "Une cuisine",
      "Un WC visiteur",
      "Une buanderie",
      "Téserve",
      "Trois terrasses",
    ],
    imgUrl: [images.villa5, images.villa6, images.villa7],
  },
  {
    category: "villa",
    specification: "Conception d'une villa de type F5",
    service: "Conception et construction",
    surface: "280 m2",
    dsc: [
      " Quatre Chambres avec douche salle d'eau ",
      "Une toilette visiteur",
      " Deux terrasses, une avant une arriere",
      "Un grand salon",
      "Une cuisine",
      "Une loge de gardien",
      "Une salle à manger",
      "Trois Terrasses",
    ],
    imgUrl: [images.villa10, images.villa11],
  },
  {
    category: "Villa",
    specification: "Conception d'une villa de type F5",
    service: "Conception et construction",
    surface: "280 m2",
    dsc: [
      " Quatre Chambres avec douche salle d'eau ",
      "Une toilette visiteur",
      " Deux terrasses, une avant une arriere",
      "Un grand salon",
      "Une cuisine",
      "Une loge de gardien",
      "Une salle à manger",
    ],
    imgUrl: images.villa9,
  },
  {
    category: "Apartment",
    specification: "Appartement de type F3",
    service: "Conception et construction",
    surface: "200 m2",
    dsc: [
      "Deux grandes chambres avec placards ",
      "Deux douches, ( dont une dans la chambre parentale)",
      "Un grand salon, (pouvant contenir séjour + salle à manger)",
      "Une cuisine",
    ],
    imgUrl: [images.apartment1, images.apartment2, images.apartment3],
  },
  {
    category: "Maison",
    specification: "Maison plein pieds de type F5",
    service: "Conception et construction",
    surface: "200 m2",
    dsc: [
      "Quatre Chambres ",
      "Une toilette visiteur",
      "Un grand salon",
      "Une salle a mange",
      "Une zone véhicule",
      "Deux Salle d'eau",
      "Un dressing dans la chambre parent",
      "Une grande cuisine avec magasin",
      "Trois terrasses",
    ],
    imgUrl: [images.house1, images.house2],
  },
  {
    category: "	Bâtiment",
    specification: "Bâtiment R+1",
    service: "Conception et construction",
    surface: "120 m2",
    dsc: [
      "Cinq Chambres",
      "Trois douches (dont une dans la chambre parentale)",
      "Un grand salon",
      "Une salle a mange",
      "Une reserve",
      "Un WC visiteur",
      "Un cuisine",
      "Un bureau",
      "Trois terrasses",
    ],
    imgUrl: [images.btm1, images.btm2],
  },
];
