import images from "./images";

const description = [
  {
    link: "/villa1",
    category: "Villa",
    specification: "Villa écologique en brique de terre",
    service: "Conception et construction",
    surface: "500 m2",
    // dsc: [
    //   "Un grand Séjour parental",
    //   "une grande cuisine",
    //   " Une reserve",
    //   "Un bureau",
    //   "Un séjour pour enfants",
    //   "Une loge de gardien",
    //   "Trois chambres",
    //   "Trois Terrasses",
    //   "Deux douches",
    //   "Une toilette visiteur",
    //   "Une buanderie extérieur",
    // ],
    // img: images.villa2,
    img: [images.villa2, images.villa1],
  },
  {
    link: "/villa2",
    category: "Villa",
    specification: "Conception d'une villa de type F4",
    service: "Conception et construction",
    surface: "250 m2",
    // dsc: [
    //   "Trois Chambres avec douche dans chacune",
    //   "une grande cuisine",
    //   " Un grand salon",
    //   "Une salle à manger",
    //   "Une cuisine",
    //   "Un WC visiteur",
    //   "Une buanderie",
    //   "Téserve",
    //   "Trois terrasses",
    // ],
    // img: images.villa5,
    img: [images.villa5, images.villa6, images.villa7],
  },
  {
    link: "/villa3",
    category: "Villa",
    specification: "Conception d'une villa de type F5",
    service: "Conception et construction",
    surface: "280 m2",
    // dsc: [
    //   " Quatre Chambres avec douche salle d'eau ",
    //   "Une toilette visiteur",
    //   " Deux terrasses, une avant une arriere",
    //   "Un grand salon",
    //   "Une cuisine",
    //   "Une loge de gardien",
    //   "Une salle à manger",
    //   "Trois Terrasses",
    // ],
    // img: images.villa10,
    img: [images.villa10, images.villa11],
  },
  {
    link: "/villa4",
    category: "Villa",
    specification: "Conception d'une villa de type F5",
    service: "Conception et construction",
    surface: "280 m2",
    // dsc: [
    //   " Quatre Chambres avec douche salle d'eau ",
    //   "Une toilette visiteur",
    //   " Deux terrasses, une avant une arriere",
    //   "Un grand salon",
    //   "Une cuisine",
    //   "Une loge de gardien",
    //   "Une salle à manger",
    // ],
    img: [images.villa9],
  },
  {
    link: "/apartment",
    category: "Appartement",
    specification: "Appartement de type F3",
    service: "Conception et construction",
    surface: "200 m2",
    // dsc: [
    //   "Deux grandes chambres avec placards ",
    //   "Deux douches, ( dont une dans la chambre parentale)",
    //   "Un grand salon, (pouvant contenir séjour + salle à manger)",
    //   "Une cuisine",
    // ],
    // img: images.apartment1,
    img: [images.apartment1, images.apartment2, images.apartment3],
  },
  {
    link: "/house",
    category: "Maison",
    specification: "Maison plein pieds de type F5",
    service: "Conception et construction",
    surface: "200 m2",
    // dsc: [
    //   "Quatre Chambres ",
    //   "Une toilette visiteur",
    //   "Un grand salon",
    //   "Une salle a mange",
    //   "Une zone véhicule",
    //   "Deux Salle d'eau",
    //   "Un dressing dans la chambre parent",
    //   "Une grande cuisine avec magasin",
    //   "Trois terrasses",
    // ],
    // img: images.house1,
    img: [images.house1, images.house2],
  },
  {
    category: "Bâtiment",
    specification: "Bâtiment R+1",
    service: "Conception et construction",
    surface: "120 m2",
    // dsc: [
    //   "Cinq Chambres",
    //   "Trois douches (dont une dans la chambre parentale)",
    //   "Un grand salon",
    //   "Une salle a mange",
    //   "Une reserve",
    //   "Un WC visiteur",
    //   "Un cuisine",
    //   "Un bureau",
    //   "Trois terrasses",
    // ],
    // img: images.btm1,
    img: [images.btm1, images.btm2],
  },
];

export default description;
